name: Build

on:
    push:
        branches:
            - master

env:
    AZURE_WEBAPP_NAME: gitlookup
    AZURE_WEBAPP_PACKAGE_PATH: "."
    NODE_VERSION: "12.x"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: install
              run: |
                  npm i
            - name: "Deploy to Azure WebApp"
              uses: azure/webapps-deploy@v1
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
